import { useState, useEffect, useCallback } from 'react'
import type { CareStrategy, DailyStrategy, CareAction } from '../../MyPlantsPage/types/plantBox.types'
import { refreshCareStrategy, toggleActionCompleted } from '../../../services/plantBoxService'

// Helper to map backend care strategy to frontend format
const mapBackendStrategyToFrontend = (backendStrategy: any, plantBoxId: string): CareStrategy | null => {
  if (!backendStrategy || !backendStrategy.next7Days) {
    return null
  }

  const mappedDays: DailyStrategy[] = backendStrategy.next7Days.map((day: any, dayIdx: number) => {
    const mappedActions: CareAction[] = (day.actions || []).map((action: any, actionIdx: number) => {
      // Map backend action types to frontend types
      const typeMap: Record<string, CareAction['type']> = {
        water: 'watering',
        fertilize: 'fertilizing',
        prune: 'pruning',
        check: 'inspection',
        protect: 'protection',
      }

      // Generate unique ID if not present
      const actionId = action._id || `action_${dayIdx}_${actionIdx}_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`
      
      return {
        _id: actionId,
        time: action.time || '08:00',
        description: action.description || '',
        reason: action.reason || '',
        completed: action.completed || false,
        type: typeMap[action.type] || 'other',
        products: action.products
          ? action.products.map((p: string | { name: string; link?: string }) =>
              typeof p === 'string' ? { name: p } : p
            )
          : undefined,
      }
    })

    return {
      date: day.date ? new Date(day.date).toISOString() : new Date().toISOString(),
      weather: {
        temp: day.weather?.temp || { min: 20, max: 30 },
        humidity: day.weather?.humidity || 60,
        rain: day.weather?.rain || 0,
        alerts: day.weather?.alerts || [],
      },
      actions: mappedActions,
    }
  })

  return {
    plantBoxId,
    lastUpdated: backendStrategy.lastUpdated
      ? new Date(backendStrategy.lastUpdated).toISOString()
      : new Date().toISOString(),
    next7Days: mappedDays,
    summary: backendStrategy.summary,
  }
}

export const useCareStrategy = (plantBox: any & { careStrategy?: any }) => {
  const [strategy, setStrategy] = useState<CareStrategy | null>(null)
  const [loading, setLoading] = useState(true)
  const [refreshing, setRefreshing] = useState(false)
  const [autoGenerated, setAutoGenerated] = useState(false) // Track if we've auto-generated

  // Load strategy from plantBox
  useEffect(() => {
    if (plantBox?.careStrategy) {
      const mappedStrategy = mapBackendStrategyToFrontend(plantBox.careStrategy, plantBox._id)
      setStrategy(mappedStrategy)
      setLoading(false)
      setAutoGenerated(false) // Reset when strategy exists
    } else {
      setStrategy(null)
      setLoading(false)
    }
  }, [plantBox])

  const refreshStrategy = useCallback(async () => {
    if (!plantBox?._id) return

    setRefreshing(true)
    try {
      const response = await refreshCareStrategy(plantBox._id)

      if (response.success && response.data) {
        const backendBox = response.data as any
        const mappedStrategy = mapBackendStrategyToFrontend(
          backendBox.careStrategy,
          plantBox._id
        )
        setStrategy(mappedStrategy)
        setAutoGenerated(true) // Mark as generated after successful refresh
      } else {
        throw new Error('Failed to refresh strategy')
      }
    } catch (err: any) {
      console.error('Error refreshing strategy:', err)
      throw err
    } finally {
      setRefreshing(false)
    }
  }, [plantBox?._id])

  // Auto-generate strategy if plant box has location but no strategy
  useEffect(() => {
    // Only auto-generate if:
    // 1. PlantBox is loaded (has _id)
    // 2. No strategy exists (neither in plantBox nor in state)
    // 3. Has location coordinates
    // 4. Not already auto-generated in this session
    // 5. Not currently loading or refreshing
    const hasStrategy = plantBox?.careStrategy || strategy !== null
    const shouldAutoGenerate = 
      plantBox?._id &&
      !hasStrategy &&
      plantBox?.location?.coordinates?.lat &&
      plantBox?.location?.coordinates?.lon &&
      !autoGenerated &&
      !loading &&
      !refreshing

    if (shouldAutoGenerate) {
      console.log('🔄 Auto-generating care strategy...')
      setAutoGenerated(true) // Prevent multiple calls
      // Auto-generate strategy in background
      refreshStrategy()
        .catch((err) => {
          console.error('Auto-generate strategy failed:', err)
          setAutoGenerated(false) // Reset on error so user can retry
        })
    }
  }, [plantBox?._id, plantBox?.careStrategy, plantBox?.location?.coordinates?.lat, plantBox?.location?.coordinates?.lon, strategy, autoGenerated, loading, refreshing, refreshStrategy])

  const toggleActionComplete = useCallback(async (dayIndex: number, actionId: string) => {
    if (!strategy || !plantBox?._id) return

    const updatedDays = [...strategy.next7Days]
    const action = updatedDays[dayIndex]?.actions.find((a) => a._id === actionId)
    if (action) {
      const newCompletedStatus = !action.completed
      action.completed = newCompletedStatus
      setStrategy({ ...strategy, next7Days: updatedDays })
      
      // Save to backend
      try {
        await toggleActionCompleted(plantBox._id, dayIndex, actionId, newCompletedStatus)
      } catch (error) {
        console.error('Error saving action status:', error)
        // Revert on error
        action.completed = !newCompletedStatus
        setStrategy({ ...strategy, next7Days: updatedDays })
      }
    }
  }, [strategy, plantBox?._id])

  return {
    strategy,
    loading,
    refreshing,
    refreshStrategy,
    toggleActionComplete,
  }
}
